- name: Wait for BIG-IP to boot up completely
  wait_for:
    host: "{{ ansible_host }}"
    port: 8443
    state: present

- name: Change BIG-IP F5 mgmt password
  bigip_command:
    provider:
      ssh_keyfile: "{{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
      transport: cli
      user: admin
      server: "{{ ansible_host }}"
    commands: "modify auth user admin password {{admin_password}}"

- name: Wait for API to be Ready
  bigip_wait:
    timeout: 300
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"
  delegate_to: localhost

# The bigip_lx_package requires rpm installed, on macOS use brew rather than pip or it won't work
- name: Install AS3
  bigip_lx_package:
    package: "{{playbook_dir}}/roles/f5_setup/files/f5-appsvcs-3.4.0-2.noarch.rpm"
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"
